Auction 2/Auction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from bid_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('signup/', signup, name="signup"),
    path('login/', login_user, name="login"),
    path('logout/', Logout, name="logout"),
    path('add_product', Add_Product, name="add_product"),
    path('view_product', view_product, name="view_product"),
    path('delete_product/<int:pid>', delete_product, name="delete_product"),
    path('product_detail/<int:pid>', product_detail, name="product_detail"),
    path('make_participants/<int:pid>', make_participants, name="make_participants"),
    path('getbidhistory/<int:pid>', getbidhistory, name="getbidhistory"),
    path('startbidding/<int:pid>', startbidding, name="startbidding"),
    path('changelivetocomplete/<int:pid>', changelivetocomplete, name="changelivetocomplete"),
    path('changeupcomingtolive/<int:pid>', changeupcomingtolive, name="changeupcomingtolive"),
    path('delete_admin_product/<int:pid>', delete_admin_product, name="delete_admin_product"),
    path('delete_category/<int:pid>', delete_category, name="delete_category"),
    path('change_status/<int:pid>', change_status, name="change_status"),
    path('delete_sub_category/<int:pid>', delete_sub_category, name="delete_sub_category"),
    path('delete_user/<int:pid>', delete_user, name="delete_user"),
    path('delete_participant/<int:pid>', delete_participant, name="delete_participant"),
    path('profile/<int:pid>', profile, name="profile"),
    path('email_verify/<int:pid>', email_verify, name="email_verify"),
    path('generateotp/<int:pid>', generateotp, name="generateotp"),
    path('admin_product_detail/<int:pid>', admin_product_detail, name="admin_product_detail"),
    path('bidder_detail/<int:pid>', bidder_detail, name="bidder_detail"),
    path('seller_detail/<int:pid>', seller_detail, name="seller_detail"),
    path('edit_product/<int:pid>', edit_product, name="edit_product"),
    path('edit_profile', Edit_profile, name="edit_profile"),



    path('load-courses/', load_courses, name='ajax_load_courses'),
    path('meetwinners/', meetwinners, name='meetwinners'),
    path('all_product/', all_product, name='all_product'),


    path('admin-home/', admin_home, name='admin_home'),
    path('loginadmin', Admin_Login, name="loginadmin"),
    path('view_seller_user/', view_seller_user, name="view_seller_user"),
    path('view_buyer_user', view_buyer_user, name="view_buyer_user"),
    path('admin_view_product', Admin_product, name="admin_view_product"),
    path('add_categary', Add_Categary, name="add_categary"),
    path('view_categary', View_Categary, name="view_categary"),
    path('add_sub_categary', Add_Sub_Categary, name="add_sub_categary"),
    path('view_sub_category', View_Sub_Categary, name="view_sub_category"),
    path('view_participants', view_participants, name="view_participants"),
    path('view_winner', View_winner, name="view_winner"),
    path('change_password', Change_Password, name="change_password"),



    path('change_user_status/<int:pid>', change_user_status, name="change_user_status"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Auction 2/bid_app/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Member_fee(models.Model):
    fee = models.CharField(max_length=20,null=True)

    def __str__(self):
        return self.fee

class AuctionUser(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=100,null=True, blank=True)
    contact = models.CharField(max_length=10,null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    user_type = models.CharField(max_length=100,null=True, blank=True)
    status = models.CharField(max_length=100,null=True, blank=True, default="pending")
    membership = models.ForeignKey(Member_fee,on_delete=models.CASCADE,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    adhar_card = models.FileField(null=True, blank=True)
    pan_card = models.FileField(null=True, blank=True)
    bank_statement = models.FileField(null=True, blank=True)
    adhar_number = models.CharField(max_length=100,null=True, blank=True)
    pan_number = models.CharField(max_length=100,null=True, blank=True)
    account_number = models.CharField(max_length=100,null=True, blank=True)
    agree = models.BooleanField(null=True, blank=True)
    email_verification = models.BooleanField(null=True, blank=True)
    otp = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name+" "+self.category.name


class Product(models.Model):
    status  = models.CharField(max_length=100,null=True, default='pending')
    bid_type  = models.CharField(max_length=100,null=True)
    payment_status  = models.CharField(max_length=100,null=True,default='pending')
    winner  = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='winner')
    user  = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='seller')
    name = models.CharField(max_length=100,null=True)
    min_price = models.IntegerField(null=True)
    final_price = models.IntegerField(null=True)
    interval_price = models.IntegerField(null=True)
    images = models.FileField(null=True)
    session = models.DateTimeField(null=True, blank=True)
    endsession = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    category = models.ForeignKey(Sub_Category,on_delete=models.CASCADE,null=True)
    parameter = models.TextField(null=True, default="{}")
    description = models.TextField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True, null=True, blank=True)
    def __str__(self):
        return self.name

class Participants(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    new_price = models.IntegerField(null=True,default=0)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.user.username+ " " + self.product.name

class ParticipantsHistory(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    new_price = models.IntegerField(null=True,default=0)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.user.username+ " " + self.product.name


class Send_Feedback(models.Model):
    profile = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message1 = models.TextField(null=True)
    date = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.profile.username

Auction 2/bid_app/views.py
from datetime import datetime, timezone
from email import message
from math import prod
from unicodedata import category
from django.shortcuts import render, redirect

from bid_app.send_email import sendemail
from .models import *
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
import random
import math
from django.conf import settings
from django.core.mail import EmailMessage

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    upcoming_product = Product.objects.filter(status="upcoming")
    closed_product = Product.objects.filter(status="closed")
    live_product = Product.objects.filter(status="live")
    d = {'upcoming_product':upcoming_product, 'closed_product':closed_product, 'live_product':live_product}
    return render(request, 'home.html', d)

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def signup(request):
    if request.method == 'POST':
        f = request.POST['fname']
        l = request.POST['lname']
        u = request.POST['uname']
        e = request.POST['email']
        p = request.POST['pwd']
        con = request.POST['contact']
        add = request.POST['add']
        d2 = request.POST['dob']
        reg = request.POST['reg']
        i = request.FILES['image']
        user = User.objects.create_user(email=e, username=u, password=p, first_name=f,last_name=l)
        mem = Member_fee.objects.get(fee="Unpaid")
        sign = AuctionUser.objects.create(membership=mem,user=user,contact=con,address=add,dob=d2,image=i, user_type=reg)
        messages.success(request, "Registration Successfully")
        return redirect('home')
    return render(request, 'signup.html')

def Logout(request):
    logout(request)
    return redirect('home')

def login_user(request):
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        sign = ""
        if user and not user.is_staff:
            login(request, user)
            messages.success(request, "Logged in Successfully")
            return redirect('home')
        else:
            messages.success(request, "Invalid credential")
    return render(request, 'login.html')


def Add_Product(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    cat = Category.objects.all()
    scat = Sub_Category.objects.all()
    sell = AuctionUser.objects.get(user=request.user)
    if request.method == "POST":
        c = request.POST['cat']
        s = request.POST['scat']
        p = request.POST['p_name']
        pr = request.POST['price']
        im = request.FILES['image']
        start = request.POST['start']
        end = request.POST['interval_price']
        desc = request.POST['desc']
        bid_type = request.POST['bid_type']
        numberofparts = request.POST['numberofparts']
        dict_val = {}
        lst = []
        for i in range(int(numberofparts)):
            parts_name = request.POST['parts_name-'+str(i)]
            parts_image = request.POST['parts_image-'+str(i)]
            myli = [parts_name, parts_image]
            lst.append(myli)
        res_dct = {i[0]: i[1] for i in lst}
        sub = Sub_Category.objects.get(id=s)
        pro1=Product.objects.create(description=desc, bid_type=bid_type, status="pending",session=start, interval_price=end, category=sub, name=p, min_price=pr, final_price=pr, images=im, parameter=res_dct, user=request.user)
        messages.success(request, "Product added successfully.")
        return redirect('view_product')
    d = {'cat': cat,'scat':scat}
    return render(request, 'add_product.html', d)


def edit_product(request, pid):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    data = Product.objects.get(id=pid)
    cat = Category.objects.all()
    scat = Sub_Category.objects.all()
    if request.method=="POST":
        c = request.POST['cat']
        s = request.POST['scat']
        p = request.POST['p_name']
        pr = request.POST['price']
        start = request.POST['start']
        end = request.POST['interval_price']
        desc = request.POST['desc']
        bid_type = request.POST['bid_type']
        try:
            i = request.FILES['image']
            data.images = i
            data.save()
        except:
            pass
        d = request.POST['desc']
        numberofparts = request.POST.get('numberofparts')
        if not numberofparts:
            numberofparts = 0
        edit_len = len(eval(data.parameter))

        lst2 = []
        for i in range(1, int(edit_len)+1):
            parts_name = request.POST['edit_parts_name-'+str(i)]
            parts_image = request.POST['edit_parts_image-'+str(i)]
            myli = [parts_name, parts_image]
            lst2.append(myli)
        dict_val = {i[0]: i[1] for i in lst2}

        lst = []
        for i in range(int(numberofparts)):
            parts_name = request.POST['parts_name-'+str(i)]
            parts_image = request.POST['parts_image-'+str(i)]
            myli = [parts_name, parts_image]
            lst.append(myli)
        res_dct = {i[0]: i[1] for i in lst}
        dict_val.update(res_dct)
        sub = Sub_Category.objects.get(id=s)
        Product.objects.filter(id=pid).update(description=desc, bid_type=bid_type,session=start, interval_price=end, category=sub, name=p, min_price=pr, final_price=pr, parameter=dict_val, user=request.user)
        messages.success(request, "Product Updated")
        return redirect('view_product')
    d = {'cat': cat,'scat':scat, 'data':data}
    return render(request, 'edit_product.html', d)




def load_courses(request):
    if not request.user.is_authenticated:
        return redirect('login')
    programming_id = request.GET.get('programming')
    courses = Sub_Category.objects.filter(category_id=programming_id).order_by('name')
    return render(request, 'courses_dropdown_list_options.html', {'courses': courses})


def view_product(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    product = Product.objects.filter(user=request.user)
    return render(request, 'view_product.html', {'product': product})


def delete_product(request,pid):
    if not request.user.is_authenticated:
        return redirect('login')
    pro = Product.objects.get(id=pid)
    pro.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('view_product')

def product_detail(request, pid):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    product = Product.objects.get(id=pid)
    return render(request, 'product_detail.html', {'product':product})

def make_participants(request, pid):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    product = Product.objects.get(id=pid)
    participant = Participants.objects.create(user=request.user, product=product)
    messages.success(request, "Added for participant successfully.")
    return redirect('product_detail', pid)

def getbidhistory(request, pid):
    if not request.user.is_authenticated:
        return redirect('login')
    product = Product.objects.get(id=pid)

Auction 2/bid_app/templates/administration/admin_product_detail.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}
{% load custom_tags %}
<div class="main-panel">
    <div class="content-wrapper">
      
      <div class="row">
        
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Product Details</h4>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="preview-list">


                    <div class="preview-item border-bottom">
                        <div class="col-md-6"><hr>
                            <h4><span class="text-muted mb-1">AuctionID</span> :  {{product.id}} </h4><hr>
                            <h4><span class="text-muted mb-1">Name</span> :  {{product.name}} </h4><hr>
                            <h4><span class="text-muted mb-1">Category</span> :  {{product.category}} </h4><hr>
                            <h4><span class="text-muted mb-1">Start Price</span> :  {{product.min_price}} </h4><hr>
                            <h4><span class="text-muted mb-1">Final Price</span> :  {{product.final_price}} </h4><hr>
                            <h4><span class="text-muted mb-1">Bid type</span> :  {{product.bid_type}} </h4><hr>
                            
                        </div>
                      
                        <div class="col-md-6" style="height:100px;"><hr>
                            <h4>  <img src="{{product.images.url}}" style="width:150px;height:140px"></h4>
                            <h4><span class="text-muted mb-1">Bid Start Time</span> :  {{product.session}} </h4><hr>
                            <h4><span class="text-muted mb-1">Description</span> :  {{product.description}} </h4><hr>
                        </div>
                     
                        
                    </div>
                  
                    
                    
                    
                  </div>
                </div>
              


              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="row">
        
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Product Specification</h4>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="preview-list">


                    <div class="preview-item border-bottom">
                        <div class="col-md-12"><hr>
                          {% for i,j in product.parameter|change_dict %}
                            <h4><span class="text-muted mb-1">{{i}}</span> :  {{j}} </h4><hr>
                          {% endfor %}
                          <h4><span class="text-muted mb-1">Status</span> :  {{product.status}} </h4><hr>
                        </div>
                        
                    </div>
                  
                    
                    
                    
                  </div>
                </div>
              


              </div>
            </div>
          </div>
        </div>
      </div>



      <div class="row">
        
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Admin Comment</h4>
                <p class="text-muted mb-1">Your data status</p>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="preview-list">


                    <div class="preview-item border-bottom">
                        <div class="col-md-6"><hr>
                            <h4><span class="text-muted mb-1">Comment </span>:  {{product.comment}}</h4><hr>
                        </div>
                      <div class="preview-item-content d-sm-flex flex-grow">
                        <form action="" method="post">
                          {% csrf_token %}
                          <textarea name="comment" placeholder="Write your comment" style="width:500px;height:100px"></textarea>
<br>
                          <input type="submit" class="btn btn-primary" value="comment">
                        </form>
                      </div>
                    </div>
                  
                    
                    
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



      <div class="row">
        
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Seller Details</h4>
                <p class="text-muted mb-1">Your data status</p>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="preview-list">


                    <div class="preview-item border-bottom">
                        <div class="col-md-6"><hr>
                            <h4><span class="text-muted mb-1">Name </span>:  {{product.user.auctionuser_set.all.0.user.first_name}} {{product.user.auctionuser_set.all.0.user.last_name}}</h4><hr>
                            <h4><span class="text-muted mb-1">Email </span>:  {{product.user.auctionuser_set.all.0.user.email}}</h4><hr>
                            <h4><span class="text-muted mb-1">Address </span>: {{product.user.auctionuser_set.all.0.address}}</h4><hr>
                            <h4><span class="text-muted mb-1">Contact </span>: {{product.user.auctionuser_set.all.0.contact}}</h4><hr>
                        </div>
                      <div class="preview-item-content d-sm-flex flex-grow">
                        <div class="col-md-6" style="height:100px;"><hr>
                            <h4>  <img src="{{product.user.auctionuser_set.all.0.image.url}}" style="width:150px;height:140px"></h4>
                        </div>
                      </div>
                    </div>
                  
                    
                    
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



      <div class="row">
        
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Winner Details</h4>
                <p class="text-muted mb-1">Your data status</p>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="preview-list">


                    <div class="preview-item border-bottom">
                        <div class="col-md-6"><hr>
                          {% if product.winner %}
                            <h4><span class="text-muted mb-1">Name </span>:  {{product.winner.auctionuser_set.all.0.user.first_name}} {{product.winner.auctionuser_set.all.0.user.last_name}}</h4><hr>
                            <h4><span class="text-muted mb-1">Email </span>:  {{product.winner.auctionuser_set.all.0.user.email}}</h4><hr>
                            <h4><span class="text-muted mb-1">Address </span>: {{product.winner.auctionuser_set.all.0.address}}</h4><hr>
                            <h4><span class="text-muted mb-1">Contact </span>: {{product.winner.auctionuser_set.all.0.contact}}</h4><hr>
                            {% else %}
                            <h4>Winner has not announced.<hr>
                          {% endif %}
                          
                        </div>
                      <div class="preview-item-content d-sm-flex flex-grow">
                        {% if product.winner %}
                        <div class="col-md-6" style="height:100px;"><hr>

                            <h4>  <img src="{{product.winner.auctionuser_set.all.0.image.url}}" style="width:150px;height:140px"></h4>
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  
                    
                    
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    </div>

    {% endblock %}

Auction 2/bid_app/templates/administration/view_winner.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<link rel = stylesheet href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>

<style>

    #example_length{
      text-align:left;
      margin-bottom:2%;
    }
  
    .dataTables_length{
      text-align:left;
    }
  
    .paginate_button{
        border:1px solid gray;
        padding:6px;
        cursor: pointer;
        color:white;
        background-color:green;
        margin:1px;
    }
  
    .dataTables_info{
      display:none;
    }
  
  </style>

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Winner reports </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">winner-user-report</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">View Winner</h4>
              
              </p>
              <div class="table-responsive">
                <table class="table table-striped" id="example">
                  <thead>
                    <tr>
                        <th>Image</th>
                        <th>winner Name</th>
                        <th>Seller Name</th>
                        <th>Winner Contact</th>
                        <th>Seller Contact</th>
                        <th>Product</th>
                        <th>Start</th>
                        <th>Payment Status</th>
                        <th>Action</th>
                      </tr>
                      </thead>
                       <tbody>
                    
                        {% for i in pro %}
                      <tr>
                    
                        <td><img src="{{i.winner.auctionuser_set.all.0.image.url}}"></td>
                        <td>{{i.winner.first_name}} {{i.winner.last_name}}</td>
                        <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                          <td>{{i.winner.auctionuser_set.all.0.contact}}</td>
                          <td>{{i.user.auctionuser_set.all.0.contact}}</td>
                          <td>{{i.name}}</td>
                          <td>{{i.session}}</td>
                          <td>{{i.payment_status}}</td>
                        <td><a href="{% url 'admin_product_detail' i.id %}"><button class="btn btn-info">Detail</button></a></td>
                        
                      </tr>
                        {% empty %}
                    <tr>
                      <td>Data Not Found</td>
                    </tr>
                        {% endfor %}
                        </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <script>
        $(document).ready(function() {
            //Only needed for the filename of export files.
            //Normally set in the title tag of your page.
            document.title='Simple DataTable';
            // DataTable initialisation
            $('#example').DataTable(
                {
                    "dom": '<"dt-buttons"Bf><"clear">lirtp',
                    "paging": true,
                    "autoWidth": true,
                    "buttons": [
                        'colvis',
                        'copyHtml5',
                'csvHtml5',
                        'excelHtml5',
                'pdfHtml5',
                        'print'
                    ]
                }
            );
        });
        </script>

{% endblock %}